server:
  port: 8080

spring:
  application:
    name: pricing-service
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  cache:
    cache-names: prices
    caffeine:
      spec: maximumSize=1000,expireAfterAccess=10m

logging:
  level:
    root: INFO
    com.bcncgroup.pricingservice: DEBUG
