CREATE TABLE IF NOT EXISTS PRICES (
  BRAND_ID INT NOT NULL,
  START_DATE VARCHAR(19) NOT NULL,
  END_DATE VARCHAR(19) NOT NULL,
  PRICE_LIST INT NOT NULL,
  PRODUCT_ID INT NOT NULL,
  PRIORITY INT NOT NULL,
  PRICE DECIMAL(10,2) NOT NULL,
  CURR VARCHAR(3) NOT NULL
);
