CREATE TABLE IF NOT EXISTS PRICES (
  ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  BRAND_ID INT NOT NULL,
  START_DATE TIMESTAMP NOT NULL,
  END_DATE TIMESTAMP NOT NULL,
  PRICE_LIST INT NOT NULL,
  PRODUCT_ID INT NOT NULL,
  PRIORITY INT NOT NULL,
  PRICE DECIMAL(10,2) NOT NULL,
  CURR VARCHAR(3) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_prices_product_brand_dates_priority
  ON PRICES (PRODUCT_ID, BRAND_ID, START_DATE, END_DATE, PRIORITY);
